# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fbfc6a332cd97474448b78ab2e5b35a2c5fc4835f09850497c213ebb3da148783fd23a174b2e644852a3e813ac8cd2ee49f0c1b9b301866578d3083c6ebd94a

test:
  secret_key_base: 8cd261fe73e37b9e7dd2ac11761e65d28380fd9a0726f00f5156bc518e3d5f2c1ede90aa530d961a6f1b8a091ee0eb60ec2564681c581bb57e00fe08aad1434e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
